{{- if .Values.hydra.registrationToken }}
apiVersion: v1
kind: Secret
metadata:
  name: hydra-operator-registration
  namespace: {{ include "hydra-operator.namespace" . }}
  labels:
    {{- include "hydra-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.hydra.registrationToken | quote }}
{{- end }}
