apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "hydra-operator.namespace" . }}
  labels:
    {{- include "hydra-operator.labels" . | nindent 4 }}
