apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hydra-operator
  labels:
    app.kubernetes.io/name: hydra-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hydra-operator
subjects:
  - kind: ServiceAccount
    name: hydra-operator
    namespace: hydra-operator-system
